### ISSUE TITLE
Redirect HTTP to HTTPS

### ISSUE THREAD

**Issue by yanokwa** [opendatakit/central#54] opened 2019-02-14 20:11 UTC
http://sandbox.central.opendatakit.org does not redirect HTTP to HTTPS. It should, and I think we might want to make this the default behavior on all installs.

**Comment by clint-tseng** [comment] 2019-02-14 20:16
oh, it's supposed to. hum.

**Comment by clint-tseng** [comment] 2019-02-18 22:49
duplicate of #56.

**Closed by clint-tseng** 2019-02-18 22:49 UTC
